version: "3"

services:
    rabbitmq:
        build:
            dockerfile: ./Dockerfile
            context: ./rabbitmq
        ports:
            - 5672:5672
            - 15672:15672 # RabbitMQ UI - credentials: guest/guest
        hostname: rabbitmq
        # volumes:
        # - ./rabbitmq/configuration:/etc/rabbitmq/conf.d # Uncomment when we're ready to use a custom config file
        healthcheck:
          test: rabbitmq-diagnostics -q check_running
          interval: 30s
          timeout: 30s
          retries: 3

    ui:
        build:
            dockerfile: ./Dockerfile
            context: ./ui
        ports:
            - 8080:80
        hostname: ui
        environment:
            - API_URL=${API_URL}
        depends_on:
            - api

    api:
        build:
            dockerfile: ./api/Dockerfile
            context: ./
        ports:
            - 8081:80
            - 8082:443
        hostname: api
        environment:
            - RABBITMQ_URL=${RABBITMQ_URL}
        depends_on:
            - rabbitmq

    worker:
        build:
            dockerfile: ./worker/Dockerfile
            context: ./
        hostname: worker
        environment:
            - RABBITMQ_URL=${RABBITMQ_URL}
        depends_on:
            - rabbitmq
